from abstract.env import ENV

JSON_RPC_PROVIDER = ENV["JSON_RPC_PROVIDER"]
UNI_CLI_PATH = ENV["UNI_CLI_PATH"]
SETTINGS_DB__DSN = ENV["SETTINGS_DB__DSN"]
PATH_DB__DSN = ENV["PATH_DB__DSN"]
SYNC_DB__DSN = ENV["SYNC_DB__DSN"]
REDIS_DSN__INFO = ENV["REDIS_DSN__INFO"]
