from abstract.env import ENV

TELEGRAM_BOT_TOKEN = ENV['TELEGRAM_BOT_TOKEN']
TELEGRAM_BOT_PASSWORD = ENV['TELEGRAM_BOT_PASSWORD']
MANAGEMENT_API_URL = ENV['MANAGEMENT_API_URL']
DB_PATH = ENV['DB_PATH']
