from abstract.env import ENV

from dotenv import load_dotenv
load_dotenv()
RABBITMQ_DSN__CONSUMER = ENV.get("RABBITMQ_DSN__CONSUMER")
RABBITMQ_QUE__CONSUMER = ENV.get("RABBITMQ_QUE__CONSUMER")

TELEGRAM_BOT_PASSWORD = ENV.get("TELEGRAM_BOT_PASSWORD")
TELEGRAM_BOT_TOKEN = ENV.get("TELEGRAM_BOT_TOKEN")

REDIS_DSN__SYNC = ENV.get("REDIS_DSN__SYNC")
REDIS_DSN__SETTINGS = ENV.get("REDIS_DSN__SETTINGS")

DB_PATH = ENV.get("DB_PATH")
