from abstract.env import ENV

MESSAGE_BROKER__DSN = ENV["MESSAGE_BROKER__DSN"]

TELEGRAM_BOT_PASSWORD = ENV["TELEGRAM_BOT_PASSWORD"]
TELEGRAM_BOT_TOKEN = ENV["TELEGRAM_BOT_TOKEN"]

DB_PATH = ENV["DB_PATH"]

